### ISSUE TITLE
300 deg extruder firmware

### ISSUE THREAD

**Issue by matt3usz** [ThomasToka/MarlinFirmware#10]
hi, i cannot find firmware that will allow my full metal extruder reach 300 deg. your firmware limiting to 260 deg . 
edit: printer ender s1 plus

**Comment by ThomasToka** [comment]
Not a mainboard firmware problem.

Please learn basics of conversations and bug reporting.

Out of this weired you say i read that you probably have a Ender 3 S1 Plus that you know nothing about. Especially about the used screen firmware and its limitations.

**Comment by ThomasToka** [comment]
Fix is: install ender 3 s1 pro screen firmware.
