### ISSUE TITLE
Touchscreen is freezing

### ISSUE THREAD

**Issue by LVianaS2** [ThomasToka/MarlinFirmware#12]
Hello, the touchscreen is freezing on the leveling page. When I touch the buttons, it makes a beeping sound, but it doesn't respond to commands.

**Comment by ThomasToka** [comment]
Cant reproduce. Works as intended.

Please post on my discord in the #bugreport channel with a short video where it exactly happens.

I have only seen something with cable bricks that accassionally accure and lead to inconsitent results.

**Comment by ThomasToka** [comment]
And: Are you sure both screen and mainboard updated to rc3 ?

**Comment by LVianaS2** [comment]
> And: Are you sure both screen and mainboard updated to rc3 ?

Yes, I updated both firmware, both on the screen and on the motherboard.

**Comment by LVianaS2** [comment]
I added the video to your discord

**Comment by ThomasToka** [comment]
After intersecting you complain:

- there is no freeze
- the button only reacts if the steppers were deactivated
- as entering leveling page automatically does a G28 the steppers are in a "valid known position".

so everything works as intended.

to testwise activate the button:

- send M84 over a terminal or sender
- push the home button
- axes will be homed once and are back in a "valid and known position"
- after this the button will only beep again till the stepper position is again invalid 
- the beeping can´t be supressed.

so: nice try with a bug. but it all works like intended. a bit unlucky that i cant suppress the beep, but thats how it is.
