### ISSUE TITLE
upgraded to v001 official release firmware  5x5abl and i have 3s1pro 

### ISSUE THREAD

**Issue by 0Locke0** [ThomasToka/MarlinFirmware#14]
Hi,
i do not see a virtualization of the mesh like it is listed in the features of your release, is that an issue or did i something wrong?

**Comment by ThomasToka** [comment]
yes sure. please read the installation.txt and install the screen firmware too.

**Comment by 0Locke0** [comment]
worked : )

**Comment by ThomasToka** [comment]
great. you can also join the discord :)
