### ISSUE TITLE
File:   "Ender-3S1-3S1_Pro_HighSpeed_E3S1PROFORKBYTT_V001"  for  s1 plus too?

### ISSUE THREAD

**Issue by Delba84** [ThomasToka/MarlinFirmware#15]
in the case of this final version of MARLIN-E3S1PROFORK-BYTT. I have ender 3 s1 plus, but the file "Ender-3S1-3S1_Pro_HighSpeed_E3S1PROFORKBYTT_V001" works for the plus? or do you have another file for the plus?

**Comment by ThomasToka** [comment]
yes, sure, it works on both as i unified them.
