### ISSUE TITLE
autorun crtouch

### ISSUE THREAD

**Issue by fabiociconello** [ThomasToka/MarlinFirmware#16]
Olá Tomas.

Primeiramente obrigado pelo firmware, isso ajudou muito a comunidade, continue esse bom trabalho.

Minha duvida é qual o objetivo do "Autorun do CRTouch", para que serve?

Obrigado

**Comment by ThomasToka** [comment]
Sorry i only can support in english.

It seams you are asking about the autorun on the cr touch site. it measures your tramming points automatically. they should all be nearly the same to have a flat surface. 

please don’t use github issues for simple questions. you can join my discord for simple questions.

**Comment by fabiociconello** [comment]
Hi Tomas

How can I join with you on discord?

Thanks and I'm sorry to use the git hub issues


Em qui., 29 de jun. de 2023 18:19, ThomasToka ***@***.***>
escreveu:

**Comment by ThomasToka** [comment]
https://discord.com/invite/Fh4jsUJWe6
