### ISSUE TITLE
To help with releases

### ISSUE THREAD

**Issue by dl200010** [ThomasToka/MarlinFirmware#17]
I do not know any other way to contact, but I wanted to help out. The F1 vs F4 issue doesn't really have to be an issue. All you need to do is place the F1 bin in the root of the SD and the F4 bin in a folder labeled "STM32F4_UPDATE". This is how Creality sends out it's updates. F1 boards will only look at the root of the card for a bin, and F4 will only look into the folder I listed above. The same the screen does with "DWIN_SET" vs "private". If the code is released in a zip with "firmware-20230716-000930-E3S1Pro-abl5x5-LA-F1.bin" in the root and "firmware-20230716-000249-E3S1Pro-abl5x5-LA-F4.bin" in the "STM32F4_UPDATE" folder, then the machine will pick which one it needs. No need to worry about messing up the board by flashing F1 on F4 board or vise versa. If you want to verify this, then go to the Creality website and download the firmware for the Ender 3 S1 Pro, look into the zip, and read the instructions. It tells you to put the F1 bin and the STM32F4_UPDATE (which has the F4 bin in it) folder on to the SD card to update.

**Comment by ThomasToka** [comment]
Well. One flower for you.. 

But: Did you read the installation.txt ?

**Comment by ThomasToka** [comment]
As i have multiple releases i wont deploy a zip file for each printer/version with a bin and stm folder/bin.
If a user is not able to flash his/her/its printer other support ways are open.
Of over 200 testers. Maybe one or two asked about F1/F4 version.
So this is not a problem in "my little real world".
Reading installation.txt is a absolute must do task on installation.
Thank you for taking care.

**Comment by dl200010** [comment]
Ah. I was just trying to help. It is something I have been thinking about for a while, but GitHub has no way to just message someone. I am not expecting anything to come out of this issue.

**Comment by ThomasToka** [comment]
Please join my little community. Link is also in the installation.txt
