### ISSUE TITLE
UBL100 fails after point 90 

### ISSUE THREAD

**Issue by lalalamoneyright** [ThomasToka/MarlinFirmware#18]
UBL100 fails after point 90 every time, tried M501 M502, power  cycling and repeating, checked the manual leveling. 
Pronterface gives nothing but Mesh calibration failed. 
It worked first time with no issue, no other SW changes done since then. 
![WhatsApp Image 2023-08-14 at 12 31 44](https://github.com/ThomasToka/MarlinFirmware/assets/142216590/7b426914-64ac-4759-b119-be28c4128eae)

**Comment by ThomasToka** [comment]
For now i cant reproduce.

Did you any modifications with a terminal?

![image](https://github.com/ThomasToka/MarlinFirmware/assets/117008525/f88e6ef1-bff9-45d4-bc9f-e37bf01cbb1b)

**Comment by ThomasToka** [comment]
second run also was successfull. so most probably not a firmware problem.

**Comment by lalalamoneyright** [comment]
![image](https://github.com/ThomasToka/MarlinFirmware/assets/142216590/290c1c64-7b1e-46c4-a5e4-26c662032737)

Just a no Y offset probe mount, maybe this could influence?

**Comment by ThomasToka** [comment]
yes. thats it. it wont work reliable with a 0 y offset mod.

**Comment by ThomasToka** [comment]
Show me your M503 please.

**Comment by lalalamoneyright** [comment]
I'm not near my printer rn but the offset is X46.5 Y0 that's what I changed in the config. I'll install the stock CR mount later and redo the meshing.

**Comment by ThomasToka** [comment]
I have this on my todo. But it is a bigger thing to make the probing margins "on runtime" manipulable.

So it will take some versions till it it will be fully supported.

**Comment by lin-ycv** [comment]
FYI 7x7 ubl also fails with 0 offset mod

**Comment by ThomasToka** [comment]
> FYI 7x7 ubl also fails with 0 offset mod

maybe. but its not supported. so i wont invest any time in it. sorry.

**Comment by ThomasToka** [comment]
please try the v016 builds.

i have introduced dynamic margins and mesh switch to ubl also now.

https://github.com/ThomasToka/MarlinFirmware/releases/tag/MARLIN-E3S1PROFORK-BYTT-v016
