### ISSUE TITLE
Update for both Display and Mainboard does not work

### ISSUE THREAD

**Issue by ghost** [ThomasToka/MarlinFirmware#20]
Hi, I tried to update my Ender 3 S1Plus today and followed your steps exactly but when I try to update the display firmware the screen doesnt show anything for 10min exept for the backlight that is on (and the fan so I know the printer is actually on) and then after that I tried updating the Mainboard and the printer just booted like normal. I put the bin file in the folder which is correctly named and formated to fat32 with a size of 4096 and the size of the Volume is 2048 just like you described. 

This is the back of my Display
![20230817_065502](https://github.com/ThomasToka/MarlinFirmware/assets/82883104/9dc7333d-fb11-45b2-a3c2-1292af5ec528)
and this is the  Mainboard
![20230816_175636](https://github.com/ThomasToka/MarlinFirmware/assets/82883104/12b0921d-c0e1-4771-ac8c-225f840e273b)

**Comment by ThomasToka** [comment]
- you have got a dwin display
- you have got a F4 mainboard

did you ever flashed anything with this sd card?

please show me a pic of your content of your sd card(s).

**Comment by ghost** [comment]
Thank you, for that Info. I have never flashed anything with this SD Card (I used a micro SD and an adapter for the mainboard)
![sdcard](https://github.com/ThomasToka/MarlinFirmware/assets/82883104/eb189d5a-14d7-418f-8c3f-013f3752530a)
![sc3](https://github.com/ThomasToka/MarlinFirmware/assets/82883104/8d610fcb-d072-4ea9-8804-3b8c1bc88847)
![sdcard2](https://github.com/ThomasToka/MarlinFirmware/assets/82883104/bd44b7f8-d29a-45da-927f-ddc45cb1736f)

**Comment by ThomasToka** [comment]
ok the content of the cards looks correct.

please try with another card the same way you did with this card.

i have noticed that some cards simply dont work. one cant say if cheap or expensive.. for me the cheapest work best.

**Comment by ghost** [comment]
Okay sure will do that, I will report back, thanks for all your help already

**Comment by ghost** [comment]
Okay with a different SD card it worked like a charm, thanks. Now only one more question since the wiki isnt really populated yet, where can I find more information about what I am able to do with this firmware and what all the functions do. Also is Host Action Commands enabled?

**Comment by ThomasToka** [comment]
i will close this as you can ask questions on the discord.

happy printing.
