### ISSUE TITLE
X Max Acceleration limited to 3000.00

### ISSUE THREAD

**Issue by lalalamoneyright** [ThomasToka/MarlinFirmware#21]
Hello! Is it possible to up the maximum acceleration values? It seems I cannot go bigger than 3000, even if the menu on the printer allows me and reports 9000. I am trying to run RingingTower for Input Shaping calibration. 

![image](https://github.com/ThomasToka/MarlinFirmware/assets/142216590/4ce27a6c-0fe4-4990-9ed2-7934d3b7aaa6)

**Comment by ThomasToka** [comment]
will have a look at it for v007.

this works like intended. but input shaping calibration is a good point to lift it.

**Comment by ThomasToka** [comment]
```
>>> M201 X9999.00 Y9999.00 Z100.00 E9999.00
SENDING:M201 X9999.00 Y9999.00 Z100.00 E9999.00
ok P15 B7
>>> M201
SENDING:M201
  M201 X9999.00 Y9999.00 Z100.00 E9999.00
```

implemented up to 9999 as the display does not allow bigger integers. z will stay at 100 max as it is not needed for input shaping calibration.

will be part of v007.

**Comment by lalalamoneyright** [comment]
Do you mind sharing a test build? I really want to set up Input Shaping xD Kind regards

**Comment by lalalamoneyright** [comment]
Nvm I built my owm from v006. Thanks for your support looking forward for v007 and a sound off toggle that's working! Keep up this amazing work!
