### ISSUE TITLE
Preview does not work in OrcaSlicer

### ISSUE THREAD

**Issue by cybertino** [ThomasToka/MarlinFirmware#26]
Looks like Orca generates thumbnail in PNG format which does not seem to be supported in Creality Ender 3 S1 Pro.

**Comment by cybertino** [comment]
A workaround for this could be:

- decode base64 of the thumbnail into bytes
- load bytes into Pillow instance and convert it into JPEG
- encode JPEG into base64

The main inconvenience (apart from being slower) is that you would need to install the [Pillow package](https://pillow.readthedocs.io/):

```
pip install Pillow
```

If you think that it's ok then I can try to work on a prototype.

**Comment by ThomasToka** [comment]
![grafik](https://github.com/ThomasToka/MarlinFirmware/assets/117008525/481f39a5-3eb0-4272-a46f-55e8b281b8e5)

the problem is more general i think. can you generate at all with it?

**Comment by ThomasToka** [comment]
ah me stupid. i had a typo in my file.

I will now have a look regarding png jpg change..

**Comment by ThomasToka** [comment]
I have developed a matching script, updated the script in the repo and updated the instructions in the wiki.

thanks for reporting.

**Comment by cybertino** [comment]
Awesome!

Thanks for fixing @ThomasToka!

**Comment by lin-ycv** [comment]
Question, Orca (1.9) can output JPG format, but it doesn't seems to work with the firmware
what's the difference between the jpg of Orca and jpg of the script?

**Comment by ThomasToka** [comment]
Please use the provided instructions:

https://github.com/ThomasToka/MarlinFirmware/wiki/Gcode-preview#orca-slicer

Orca had once only PNG support.

So we use this and convert it on the fly. JPG directly set won´t work.
