### ISSUE TITLE
ubl7x7 leveling shows 98% on finish

### ISSUE THREAD

**Issue by beroliv** [ThomasToka/MarlinFirmware#3]
Leveling stops at 98% with the 7x7 mesh on Ender 3 S1 pro

**Comment by ThomasToka** [comment]
Try ubl5x5 please. Will verify ubl7x7 in some minutes.

**Comment by ThomasToka** [comment]
An please show me your m503 output.

**Comment by beroliv** [comment]
i level again and try to catch m503

**Comment by ThomasToka** [comment]
yes please. mine is at 52% now ;)

**Comment by ThomasToka** [comment]
Any upgrades like zero y offset mode or something like that?

**Comment by beroliv** [comment]
no i dont know that something exist :-)

**Comment by beroliv** [comment]
there is another problem but dont know to explain in english

**Comment by beroliv** [comment]
there is no 503, the printer just stops and wait
how about yours?

**Comment by ThomasToka** [comment]
i can confirm the 98%. I will try something.. give me 10 minutes.

m503 is the output of your setting sent through a terminal.

but as you dont have any modifictions and i can reproduce this i dont need the output then.

my tests started.

**Comment by beroliv** [comment]
Try the ubl5x5

**Comment by beroliv** [comment]
ocotoprint shows you the bed leveling even it is not finish

**Comment by beroliv** [comment]
can we have a chat somewehere??

**Comment by ThomasToka** [comment]
add me on facebook

**Comment by beroliv** [comment]
i send you a msg, im not really a Fazebugger

**Comment by ThomasToka** [comment]
5x5ubl works. i think it will have something to do with the final accounting of the percentage.

technically the ubl7x7 works.

**Comment by ThomasToka** [comment]
The bug has been fixed and a fixed version is available with the next bugfix release.

The bug is documented under the following shortcode in the changelog:

[MARLIN-E3S1FORK-BYTT-fix3] ubl7x7 finished percentage does not match and is stuck at 98%. With this release this visual bug is fixed.

I will let this open till the bugfix release has been pushed. Estimated releasetime 02.04.2023 12.00 CET.

**Comment by ThomasToka** [comment]
[[MARLIN-E3S1FORK-BYTT-2]](https://github.com/ThomasToka/MarlinFirmware/commit/c15723371fc398cf65b7258edce4634ecf06ea32) 

has been released fixing this issue with [MARLIN-E3S1FORK-BYTT-fix3].

i will close this now.

thank you for finding and reporting this visual bug.
