### ISSUE TITLE
Changing print settings during printing causes short pause while saving them to eeprom

### ISSUE THREAD

**Issue by DjordjeMandic** [ThomasToka/MarlinFirmware#32]
For example increasing print speed causes print to pause for a second which results in blob and oozing like with power loss recovery. 

v013

![image](https://github.com/ThomasToka/MarlinFirmware/assets/6750655/a816eea8-4401-4d86-a8cd-701c9c6685d3)

**Comment by ThomasToka** [comment]
Sorry, just tried it and cant reproduce it.

- go to my discord
- go to the #reference-gcode channel
- pic one of the cubes there
- print this gcode and change settings while printing

does it happen with this also?
