### ISSUE TITLE
Screen firmware from v012 onwards keeps rebooting

### ISSUE THREAD

**Issue by cybertino** [ThomasToka/MarlinFirmware#33]
Last screen version that worked for me is v011. v012 and v013 keep rebooting.

I am not sure how I can extract details about what goes wrong.

**Comment by ThomasToka** [comment]
did you update your screen once to the creality f28 screen firmware?
did you install the matchin mainboard firmware also?

**Comment by cybertino** [comment]
I used previously installed v009. Should I install original firmware before installing it?
Yes I installed v013 mainboard firmware.

**Comment by ThomasToka** [comment]
Please read the installation.txt. installing the F28 creality screen once with the firmware.zlib is mandatory as of v008 to activate new features on the dacais.

**Comment by cybertino** [comment]
Ok, I was able to install it on top of v011.
