### ISSUE TITLE
Some buttons on the touch screen (such as Leveling) don't do anything

### ISSUE THREAD

**Issue by Berzeger** [ThomasToka/MarlinFirmware#35]
Hi, in the latest firmware (v016) on my S1 Plus I cannot access the leveling page through the touchscreen. The display beeps when I touch it, but nothing else happens. I also can't access the settings where you should be able to turn the sounds on and off (the same problem as with the leveling).
I was previously using synman's firmware.
This was my process:

1. While still having synman's firmware installed, I upgraded my screen firmware to the official 1.0.3.
2. I then upgraded the screen firmware using Ender-3S1_Pro_HighSpeed_E3S1PROFORKBYTT_Pro_Plus_v016.
3. After that, I installed firmware-20231104-175341-E3S1Plus-abl-v016-F4.bin.
4. I verified everything in the About screen on my printer.

If I manually run G28 and then G29, the display successfully enters the leveling menu and then immediately begins the autoleveling process, but it's still annoying. Note that while in this menu, the CR-touch icon on the display suffers from the same issue - it beeps, but does nothing else.

Is this just my issue, or is something wrong with the firmware? Note that I haven't used any previous versions (I've just discovered Thomas' firmware and decided to give it a go since it is being actively maintained).

Thanks!

**Comment by ThomasToka** [comment]
Hello, look at the about page. You should see in the Screen FW field also my firmware.
Please show a pic of your about page.

**Comment by Berzeger** [comment]
Wow, thanks for such a swift reply!
This is my about screen:
![WhatsApp Image 2023-11-10 at 13 09 21_44c6dd8d](https://github.com/ThomasToka/MarlinFirmware/assets/6607148/93e39cff-9a3c-4bfa-a41b-88bf5f3ce9d9)

Also, I see these four weird squares on the home screen:
![WhatsApp Image 2023-11-10 at 13 09 21_0bfb8807](https://github.com/ThomasToka/MarlinFirmware/assets/6607148/b3865e1d-a17f-4298-8ed5-7fc80bd6a3e2)

Now when I think of it... it shouldn't really say 2.1.2-+A in the F/W VER, right?

**Comment by ThomasToka** [comment]
You need to install my mainboard firmware also.

**Comment by Berzeger** [comment]
That's what I thought I did in step 3, but I guess something went wrong. Sorry about that. I'll put the SD card in the printer once more and will get back to you with results.

**Comment by ThomasToka** [comment]
No Problem. I am here to Support you. We have also a great discord Server with a bunch of users. Link is in the installation.txt.

**Comment by Berzeger** [comment]
I did the process again and it works and looks awesome. I don't know why the printer didn't install it the first time, but I should have checked more thoroughly instead of creating a GitHub ticket. Thank you very much and I apologize again... I guess having a 2 year old crying through the night doesn't help my cognitive processes. :)
I'll check out the Discord server!
