### ISSUE TITLE
Trouble with screenfirmware

### ISSUE THREAD

**Issue by J-Tevop** [ThomasToka/MarlinFirmware#37]
Hi,

No idea if it should post it here, sorry in advance. I am a little lost on the screen firmware.

Mainframe is working perfectly fine. The screen does not seem to update.

![screen1](https://github.com/ThomasToka/MarlinFirmware/assets/57175830/ed9634a0-8688-4b3e-a68c-c9b0f4c2f5a6)

![screen2](https://github.com/ThomasToka/MarlinFirmware/assets/57175830/e1e77430-70a1-4513-ac26-9e6a4652bb44)

After following your instructions the firmware version doesn't update. Any ideas?

**Comment by ThomasToka** [comment]
Hello,
Your card seems not to be formatted correctly.
Please have a look im the wiki.
https://github.com/ThomasToka/MarlinFirmware/wiki/Installation-%E2%80%90-screen-firmware

**Comment by ThomasToka** [comment]
You can also join the discord for Support.

**Comment by J-Tevop** [comment]
Hi,

Thanks for the quick response.

I just did that. No difference, unfortunately...

**Comment by ThomasToka** [comment]
Did you Partition your sd card to 2gb like described in the wiki?

**Comment by J-Tevop** [comment]
Yep!

Where is the discord. Willing to join :)

**Comment by ThomasToka** [comment]
Look in the Installation.txt link is Inside.
