### ISSUE TITLE
4 and 5 points in AUX LVL screen are switched.

### ISSUE THREAD

**Issue by Duiesel** [ThomasToka/MarlinFirmware#38]
On a screen Settings -> Leveling -> AUX lvl 4 and 5 calibration points are switched in functions.
Pressing on 5 point on a screen will guide printhead to 4 point and wise versa.

**Comment by ThomasToka** [comment]
Nice catch. As this is not critical i will check it tomorrow?

Please show me a pic of your about site of your printer.

**Comment by ThomasToka** [comment]
Good morning,
i just had a look and cant reproduce this.
Please show me a pic of your About site of your printer.
Point 4 and 5 match and do what they should.
