### ISSUE TITLE
Continue printing after power outage.

### ISSUE THREAD

**Issue by KosolapbIu** [ThomasToka/MarlinFirmware#39]
Hello. After updating the firmware, printing does not continue when the power is turned off... Is there something wrong with me or does the firmware not support continued printing? Or maybe this needs to be enabled somehow? Thank you. Have a good day...

**Comment by ThomasToka** [comment]
Hello,

did you enable it either with 

```
M413 S1
M500
```

or on the main site the upper right toggle icon?

![grafik](https://github.com/ThomasToka/MarlinFirmware/assets/117008525/430c60e9-2ab0-40d6-b008-3b86d261b7f7)


Default it is not enabled.

**Comment by KosolapbIu** [comment]
Oh... it was "Off". Now I turn this to "On"... Thanks. I'm just a beginner in 3d printing. Good day!!!

**Comment by ThomasToka** [comment]
No problem.

You can also join out discord https://discord.com/invite/Fh4jsUJWe6 .

Have a sunny day.
