### ISSUE TITLE
Print Size

### ISSUE THREAD

**Issue by beroliv** [ThomasToka/MarlinFirmware#4]
is it possible to make a 270mm Z version. I make Vacum cleaner Nozzles and need somtimes a bit more than 250mm.
Printer can do 270mm i check it Manually

**Comment by ThomasToka** [comment]
Hi,
yes. The change is already covered in the changelog and will be pushed with the next major release.

[MARLIN-E3S1PROFORK-BYTT-change4] Ender 3S1 Pro build top z limit from 250mm to 270mm.

https://github.com/ThomasToka/MarlinFirmware/blob/Firmware-Binaries/Changelog.md

**Comment by ThomasToka** [comment]
[MARLIN-E3S1PROFORK-BYTT] has been released with this fix.

Thanks for reporting.
