### ISSUE TITLE
Size Bed 

### ISSUE THREAD

**Issue by isaiasemanuel22** [ThomasToka/MarlinFirmware#40]
https://github.com/ThomasToka/MarlinFirmware/blob/733d72c93c891f306565abcee0f572ea56868123/LinearAdvance_Ender3S1Pro_E3S1PROFORKBYTT_kfactor.gcode#L22C19-L22C20

Buenas , primero felicitarte y agradecerte por los hermosos firware que estas entregando. 
He notado que cuando quiero hacer impresiones a los extremos , las impresiones se salen de la cama de impresion , y es porque la Ender 3 s1 pro , es de 220mm x 220mm no supe como corrergirlo hasta que vi tu codigo. Y ahora que lo  veo nose como solucionarlo exactamente, pero logre encontrar el error.

Muchas gracias!

**Comment by ThomasToka** [comment]
Sorry. English please.

The bed size is 235x235 for the Ender 3 S1 Pro.

**Comment by isaiasemanuel22** [comment]
Hello, first of all, congratulate you and thank you for the beautiful firmware that you are delivering.
I have noticed that when I want to make prints at the extremes, the prints come off the print bed, and it is because the Ender 3 s1 pro is 220mm x 220mm. I didn't know how to correct it until I saw your code. And now that I see it, I don't know how to solve it exactly, but I managed to find the error.

Thank you so much!

**Comment by isaiasemanuel22** [comment]
Okay, my Ender 3 s1 pro has a 220 x 220 bed, how can I edit this in the firmware?

**Comment by isaiasemanuel22** [comment]
because you have many things that I love, functionalities and screens, but I can't fit the prints on the bed well due to size differences

**Comment by ThomasToka** [comment]
you are wrong. your ender 3 s1 pro has 235x235. measure it.

this here is not a support forum for simple basics like this.

first of all: read the installation.txt completely! this is covered inside of it.

- adjust your home offsets accordingly
- adjust your slicer bed size to the correct 235x235
- adjust your purge lines accordingly

the solution is not to set the firmware to a wrong value. you need to calibrate your printer correctly. simple as that.

again: read the installation.txt. all is covered in there.

if you need furter support come to the discord. the link is also in the installation.txt.

i will close this here as this is invalid and basically wrong on your site.
