### ISSUE TITLE
S1 Pro Bed Leveling UI Incorrect

### ISSUE THREAD

**Issue by DubStepMad** [ThomasToka/MarlinFirmware#41]
Hi, just used this firmware and noticed on the touch screen when leveing that position 5 and 4 are switched around.

Looking straight ahead from the printer.
- Point 5 should be the back left but its the back right.
- Point 4 should be the back right but its the back left.

**Comment by ThomasToka** [comment]
Hello,
please show me a picture of the about site of your printer.

**Comment by DubStepMad** [comment]
@ThomasToka sorry for the delay, heres a video instead as it shows the bug more: https://drive.google.com/file/d/1aoNzQetP2o7qnLgPx80r9z0I9QXNyxKZ/view?usp=drive_link

**Comment by ThomasToka** [comment]
Again: Please send me a picture of the about site of your printer.

It is clearly visible that you dont have my screen installed.

Naturally this does not work.

Please join my discord and seek for help in #installation-help .

**Comment by ThomasToka** [comment]
![image](https://github.com/ThomasToka/MarlinFirmware/assets/117008525/b049d560-6281-4498-9985-988109e8ef7a)

this is the same site in my firmware.

**Comment by DubStepMad** [comment]
> Again: Please send me a picture of the about site of your printer.
> 
> It is clearly visible that you dont have my screen installed.
> 
> Naturally this does not work.
> 
> Please join my discord and seek for help in #installation-help .

Can you link your discord so I can join as its not listed on your github profile or the repo.

**Comment by ThomasToka** [comment]
https://discord.com/invite/Fh4jsUJWe6
