### ISSUE TITLE
Extruder fan not doing anything

### ISSUE THREAD

**Issue by legros04** [ThomasToka/MarlinFirmware#42]
Hey Thomas having an issue where I get nothing out of the extruder cooler fan. the part cooler fan works fine but not the extruder cooler.

**Comment by ThomasToka** [comment]
Noone has this. So Probably Hardware.

Please show a picture of the about site of your printer.

**Comment by legros04** [comment]
this is a brand new printer arrived yesterday, i also swapped out the sprite extruder for a spare i have and the same issue happend.

**Comment by ThomasToka** [comment]
Please show the picture.

**Comment by legros04** [comment]
![photo_2023-12-11_01-29-46](https://github.com/ThomasToka/MarlinFirmware/assets/153484278/bf87e1d2-0254-49a8-b81f-66151fe5937d)
![photo_2023-12-11_01-29-49](https://github.com/ThomasToka/MarlinFirmware/assets/153484278/63d1c8e7-e251-40c8-b0d3-8e0da6014740)
![photo_2023-12-11_01-29-52](https://github.com/ThomasToka/MarlinFirmware/assets/153484278/35199579-3da5-4691-a420-3a711ef390d3)

**Comment by legros04** [comment]
both extruders are new and both work fan 2 only after firmware upgrade  (i swapped the fan 1 and 2 plugs and the extruder fan works when plugged into fan 2 but then the part cooler fan does not work)

**Comment by ThomasToka** [comment]
Of the about site of your printer Please.

**Comment by legros04** [comment]
site? sorry i do not follow

**Comment by legros04** [comment]
![image](https://github.com/ThomasToka/MarlinFirmware/assets/153484278/80c21188-dc62-44ca-b770-e2ff7766527f)

**Comment by legros04** [comment]
sorry thought you said side

**Comment by ThomasToka** [comment]
There is something fishy with your machine. Hundreds of other printers work and there were no chnages in the last builds.
Downgrade to Stock firmware and check if it works with it.

**Comment by legros04** [comment]
ill go back to stock and see what happens should i go back to stock screen fw as well?

**Comment by ThomasToka** [comment]
Yes you need to.

**Comment by legros04** [comment]
ended up doing a bunch of digging and found [this](https://www.youtube.com/watch?v=Ijxh1nnUGlA&t=82s) apperently you can fry the ppm output by plugging in the laser module with the machine on. (of course i did that) and now i have no ppm to control the fan hence the fan not working.) at least i think a new board is on its way right now and i hope that is the fix. 

ps. thanks for the quick response really appreciate it

**Comment by ThomasToka** [comment]
autch. no problem. good luck and a speedy recovery.

**Comment by legros04** [comment]
thanks, also im not as well versed with these boards as you are would ppm issues stop the fan like that?

**Comment by ThomasToka** [comment]
please come over to the discord. we have a bunch of users that maybe can answer your questions.
i would say sure.. if you plugged something while the printer is on it can happen.
