### ISSUE TITLE
Missing Shortcuts (?) for Live Tramming Adjustment and Feed Rate

### ISSUE THREAD

**Issue by Ndrinta** [ThomasToka/MarlinFirmware#43]
Hello, new member here. First of all, thanks for your take, it's got loads of welcomed improvements I now use every day!
I flashed 21 after trying 20 over the last couple of weeks (I have a Pro and a Plus). 
One thing I miss though is the ability to jump to the Z-offset fine adjustments (babystepping) site or change the Global Feed Rate from the Home tab (especially after the print has started). In Creality's version I could simply tap the relative rectangular areas and access these functions straight from the Home tab. Furthermore, I can't find where to change Feed Rate at all with your firmware, is this how it should look like? Please let me know if this isn't the intended behaviour, seems more likely that something's wrong with my printers, maybe I missed some steps or I did something wrong along the way...

Background info:
My use case is "tinkerer", I mainly print my own designs of enclosures and functional stuff in general. My standard printing procedure is to run a auto bed level at every print start and live fine tuning the Z-offset during brim time; this works every time for me and I'm happy with that. I change my beds constantly (to get different finished and when using different materials) and I really need to fine tune the printer every time (because doing the bed leveling procedure once and save the Z-offset value for each bed it's simply not good enough).
Besides, depending on the maturity of the design, I might also want to rapidly speed up the print (maybe only at certain levels) to get it done faster (maybe I'm just dialing in hole spacing or tight fits) so the Feed Rate is quite important for me.
I'm now doing these things by sending G-Code to the printer as of now but I believe there should be a better way.

**Comment by ThomasToka** [comment]
hello,
i have heard of such a problem of one user in the last days.
in his case it was a bad slice. dont ask me what exactly went wrong, but he also could not open the adjust menu during printing.
he resliced his file and it worked again.
1) please come over to the discord
2) go the #reference-gcode channel
3) pic one of my cubes there and start a print
4) after the nozzle starts heating the menu should be available
5) if it still does not work post in #printing-help
