### ISSUE TITLE
Z-offset capped at -5.00

### ISSUE THREAD

**Issue by kirky1024** [ThomasToka/MarlinFirmware#44]
My Z-offset is usually around -6mm however using the touchscreen it is not possible to set the z-offset below -5.00

**Comment by ThomasToka** [comment]
You are sure that you set your z-offset at point 1 of the manual tramming site?

**Comment by kirky1024** [comment]
Well spotted,

no i didnt :)

thanks for the quick reply

**Comment by ThomasToka** [comment]
no problem. join the discord for further support.
