### ISSUE TITLE
Print status info missing

### ISSUE THREAD

**Issue by lin-ycv** [ThomasToka/MarlinFirmware#46]
Upgraded to v023 from v008, and noticed that there are stats on the print page that's not being populated.
As seen in the photo, the layer height, layers, weight stats on the bottom right is missing.
is this something I have to configure in the slicer?
![20231227_114117](https://github.com/ThomasToka/MarlinFirmware/assets/60565737/1ce8fdb7-ae6f-4949-9a25-71589d89b923)

**Comment by ThomasToka** [comment]
hello, you need to use the new printdata postprocessing scripts to generate this data into your gcode and then see it while printing.

https://github.com/ThomasToka/MarlinFirmware/wiki/Gcode-preview
