### ISSUE TITLE
Auto Leveling (G29)

### ISSUE THREAD

**Issue by ibrahimhakkicandan** [ThomasToka/MarlinFirmware#47]
hi, i recently bought a bd level sensor and did it what this page says: https://github.com/markniu/Bed_Distance_sensor/wiki/Installing-Bed-Distance-Sensor .When I try to auto-level with G29, it scans the 1st line except last point and then freezes Marlin. I have to cycle the power to get the printer back. Also no error is reported. I have ender 3 s1 pro with the f4 chip. also  i cant leveling from machine, i have to use pronterface to send gcode commands. when i send g29 first it directly start somehow when it reaches the edge then doing auto home after that it start leveling and stucks at the edge with BD_SENSOR_PROBE_NO_STOP defined. if not defined same sceniario but this time tries 4 times after auto home then stucks. I also tried with the default config files from marlin same again. There is a guy who suffered this problem found solution and says "I found the problem! It appears there is a bug in the current version of Marlin-bugfix-2.1.x (02010300) where it uses Z_STOP_PIN, rather than Z_MIN_PROBE_PIN in some parts of the leveling code, including "Real Time Leveling". Changing Z_STOP_PIN to the same as Z_MIN_PROBE_PIN resolved the issues." but this didnt work either in my case.

There is one more thing and i cant compile the files you provide the only file i can compile is that the "e3s1ppro_abl_personal" one

**Comment by ThomasToka** [comment]
```
//
// Limit Switches
//
#define Z_STOP_PIN                          PC14

#ifndef Z_MIN_PROBE_PIN
  #define Z_MIN_PROBE_PIN                   PC14  // BLTouch IN
#endif
```

i dont see Z_STOP_PIN at all in the bedleveling code.

sorry not supported hardware. 

you can dig my sources. but this is nothing i want to spend my time on.
