### ISSUE TITLE
Discord

### ISSUE THREAD

**Issue by Matisak** [ThomasToka/MarlinFirmware#48]
Hi, im having some problems! How can I reach you? any discord or only here?

My printer (ender 3 s1 pro) on the v23 does not appear any info almost like you can see and also does not show thumbnails, I have 2(1 32px and other 400px), Not sure what could be the problem.

![tempImagexrJXzV](https://github.com/ThomasToka/MarlinFirmware/assets/87875731/3d6e1868-9a6d-4bfe-8d0a-db112e7d7e28)
<img width="719" alt="image" src="https://github.com/ThomasToka/MarlinFirmware/assets/87875731/e0a3d107-23ae-42f1-82b0-8f9810e1886e">

Sorry if I comment on the wrong place im new to git!

**Comment by ThomasToka** [comment]
hello,
you need to use my "printdata" postprocessing script.
with those you have nothing will work.
https://github.com/ThomasToka/MarlinFirmware/wiki/Gcode-preview#cura-5x
https://discord.com/invite/Fh4jsUJWe6

**Comment by Matisak** [comment]
Thank you so much! I probably missed something! works perfectly!
![tempImagevwQZCQ](https://github.com/ThomasToka/MarlinFirmware/assets/87875731/834a39f5-525a-4b73-95dc-250d4ad79d63)
