### ISSUE TITLE
Exit adjustment menu causes print to lag

### ISSUE THREAD

**Issue by lin-ycv** [ThomasToka/MarlinFirmware#50]
As seen in the video, going into the menu and making adjustments all work fine, but as soon as i click back, the printer will lag/pause for a few seconds
this is on the v23, was not an issue back on v8

https://github.com/ThomasToka/MarlinFirmware/assets/60565737/2e15dc84-0088-4696-bf69-97a2657fe623

**Comment by ThomasToka** [comment]
Thx for reporting.

Have adjusted the process. Dont know if it is it but maybe ;)

Please check this after v024 release again and report if its fixed.
