### ISSUE TITLE
leveling bug

### ISSUE THREAD

**Issue by taintremover** [ThomasToka/MarlinFirmware#51]
I have changed the location of the probe on my s1 pro to the other side of the extruder. I fixed it in the settings menu, in probe offset. Now when I go to level the bed, it will not let me do cr touch probing in manual. It will do a corner. Then will will show that is at 0. The center is the only one that will show a reading. If I do auto leveling, it will show the readings as it doses it. Once it is done all of the readings disappear. I'm on e3s1pro-ubl-v024. I have included a video documenting my problem.  Please let me know if there is any other info you need or how ever I may help you. 

p.s. Im sorry that the video is rotated. When I compressed the video to make it fit as an attachment, it rotated it.

**Comment by ThomasToka** [comment]
i dont see a video.
please give me the following values you have set:
probe offsets x an y
home offsets x an y

**Comment by taintremover** [comment]
Probe
X is 32.5
Y is 0.20
Home
X is -5.0
Y is -5.0

**Comment by ThomasToka** [comment]
I can confirm that it does not work with a positive probe offset atm.

I dont know if i manage this to be working with the next release.

So for now its unsupported.

Revert to a firmware that works for now.
Or change your 0 y offset to one on the left side.

**Comment by taintremover** [comment]
I just want to say thanks for all your hard work. I really do love the firmware you put out. Keep up the great work!!!

**Comment by ThomasToka** [comment]
Hello are you on my discord? If not please join and post in #support.. i have a testbuild for you.

**Comment by taintremover** [comment]
what is your discord channel?

**Comment by ThomasToka** [comment]
https://discord.com/invite/Fh4jsUJWe6
