### ISSUE TITLE
Script issue with E3S1PROFORKBYTT_printdata_crealityslicer_thumbnail.py

### ISSUE THREAD

**Issue by Pweber413** [ThomasToka/MarlinFirmware#52]
E3S1PROFORKBYTT Thumbnail does not show up after placing the file into the postprocessing plugin script folder. I have restarted 
 Creality slicer 4.8.2 but that script does not appear in the list. 

I did try the file E3S1PROFORKBYTT_Thumbnail.py and it did show up in the list and functioned well.

Any suggestions?

**Comment by ThomasToka** [comment]
C:\Program Files\Creality Slicer 4.8.2\plugins\PostProcessingPlugin\scripts

this is the right folder for the script. you can only have one of them in your folders. check if you have the old script somewhere else maybe in AppData/Roaming.

**Comment by Pweber413** [comment]
Thank you for the quick response, I'll check for another copy.

Have a great weekend
