### ISSUE TITLE
Updating from v014

### ISSUE THREAD

**Issue by DDdotDE** [ThomasToka/MarlinFirmware#53]
Heyy,

I have v014 of your firmware installed and noticed that you were workin real hard and we now have a v024 version of the firmware.

Is it save to update straight to v024 from v014 or should I update to any prior version first

In best regards

DD_DE

P.S.
I have the Ender 3 S1 PRO

**Comment by ThomasToka** [comment]
You can upgrade to the last version directly.

**Comment by DDdotDE** [comment]
Good, Thank you for the quick response (and all the effort)
