### ISSUE TITLE
Offer

### ISSUE THREAD

**Issue by SnZ4iter** [ThomasToka/MarlinFirmware#54]
Good afternoon, your firmware is very good, I wanted to know/suggest adding a “print again” button on the home page together with the print completion button, if possible.
Best regards, 4iter

**Comment by ThomasToka** [comment]
maybe sometime. but its not planned for now :)

**Comment by mikep1998** [comment]
Yes I would like that too.

Lots of times I abort the print on the first layer and would like to restart the same print from the beginning.

Thanks
Mike


From: SnZ4iter ***@***.***>
Sent: Monday, January 22, 2024 11:54 AM
To: ThomasToka/MarlinFirmware ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ThomasToka/MarlinFirmware] Offer (Issue #54)


Good afternoon, your firmware is very good, I wanted to know/suggest adding a “print again” button on the home page together with the print completion button, if possible.
Best regards, 4iter
