### ISSUE TITLE
error message

### ISSUE THREAD

**Issue by UncheckedHook66** [ThomasToka/MarlinFirmware#56]
I understand this may not be a problem on your end i just don't know what to do as it errors our everytime trying to load firmware onto sd card formatted to specifications on the Readme.txt file. I  was wondering if you may be able to provide insite into this.

**Comment by ThomasToka** [comment]
macos user?

**Comment by UncheckedHook66** [comment]
sorry im not the best with technical terms, what does that mean

**Comment by UncheckedHook66** [comment]
![Screenshot 2024-01-25 170122](https://github.com/ThomasToka/MarlinFirmware/assets/83117100/727fb282-5f46-4815-96b1-e2146f6270bc)
i have provided a file to show the error message, this happens on copying any of the files

**Comment by ThomasToka** [comment]
ok its windows. you have an unpacked folder on your pc and trying to copy the creality stock firmware gives this message?

**Comment by ThomasToka** [comment]
please join my discord and screeeaaaam in #installation-help.

we can make a short anydesk session then.

https://discord.com/invite/Fh4jsUJWe6

**Comment by UncheckedHook66** [comment]
i will do that now thank you
