### ISSUE TITLE
Trying to create gcode preview Orca Slicer 1.9

### ISSUE THREAD

**Issue by RogueCryptic** [ThomasToka/MarlinFirmware#57]
I've been trying to get the gcode preview function in Orca Slicer to work and it keeps giving me errors. I'm using TT 23 currently on my S1 Plus. I've followed the directions via the Wiki but still keep getting errors. I'm a few months into 3D printing so not the brightest at some of this stuff.

![Orca Slicer gcode preview](https://github.com/ThomasToka/MarlinFirmware/assets/157967252/41249676-d19f-414f-8763-34c215a51551)
![Orca Slicer gcode preview failed](https://github.com/ThomasToka/MarlinFirmware/assets/157967252/1534a357-096f-4735-ba14-6f5132568aa3)

**Comment by ThomasToka** [comment]
Please do basic debugging steps like described in the wiki:

https://github.com/ThomasToka/MarlinFirmware/wiki/Gcode-preview#appendix-2-debugging-steps-in-case-of-failures

For further support please join the discord i will help you.
