### ISSUE TITLE
Bed Mesh points 

### ISSUE THREAD

**Issue by Rustie0125** [ThomasToka/MarlinFirmware#58]
I used the bed mesh, and chnaged the standard point count to 10x10. It still works but I cannot chnage it back. I chnage to 6 or 8 and when the probing starts it reverts to 10x10 point.

**Comment by ThomasToka** [comment]
sure. by design only 5, 7 and 10 are valid.

**Comment by Rustie0125** [comment]
So why is there no message to show that  or change the option between 3 different pre sets ?

**Comment by ThomasToka** [comment]
we dont have space for such games :(
