### ISSUE TITLE
The E3S1PROFORKBYTTT Thumbnails plugin, images in PrintJobHistory do not work

### ISSUE THREAD

**Issue by joseto1298** [ThomasToka/MarlinFirmware#64]
The images do not work with the Print Job History plugin, it would be a possible fix to make it work, in case it works with Slicer Thumbnails

![Captura](https://github.com/ThomasToka/MarlinFirmware/assets/85197083/3d653f31-1d51-4d0f-853d-7f0a5e16054f)

**Comment by ThomasToka** [comment]
not my job to support my thumbnail format in another plugin.
the other plugin needs an update.
sorry.
