### ISSUE TITLE
ABL mesh is not saving or is being ignored by the printer. 

### ISSUE THREAD

**Issue by Cdewitt70** [ThomasToka/MarlinFirmware#65]
Ender 3 S1 Plus running this firmware on printer and touchscreen

I can see when I run Bed Visualizer in octo it is presenting values and saving them to EEPROM. But when the printer is doing the first layer its ignoring and just printing as if theres no CR Touch attached. 
Been chasing this issue trying to figure out why it wont compensate and I have narrowed it down to being the firmware as the issue. As my other Ender 3 Pro with octo is running fine and using the bed mesh thats saved.

**Comment by ThomasToka** [comment]
it works as expected. you need to calibrate your printer better.
