### ISSUE TITLE
Print button not working

### ISSUE THREAD

**Issue by sudoaptinstall** [ThomasToka/MarlinFirmware#68]
The print button on the screen does not work. Every single button in the system works except it. I want to print with SD card but I cant because the Print button does not work when clicked. For now, I can only print via USB cable

**Comment by ThomasToka** [comment]
You dont have my screen firmware installed.
Have a look at the about site of your printer.
You should see a qrcode and v025 as screen version.
If you need help please come to the discord.

**Comment by sudoaptinstall** [comment]
I do have your screen firmware installed, printer says: (Screen VER: v2. 0. 0-v025-byTT).

**Comment by ThomasToka** [comment]
Please show a pic of the about site.

**Comment by sudoaptinstall** [comment]
![20240310_194210](https://github.com/ThomasToka/MarlinFirmware/assets/93219477/0ac3a10d-57a3-4dec-bff9-93a1bcda840e)

**Comment by ThomasToka** [comment]
The something else is fishy. 

Hundreds of users use it. Reset you printer. If this does not help please go to my discord. Post this in #printing-help.

We will try to help you.

**Comment by sudoaptinstall** [comment]
Where do I find the Discord link?

**Comment by ThomasToka** [comment]
installation.txt

**Comment by sudoaptinstall** [comment]
Thank you.
