### ISSUE TITLE
Setting the flow during printing

### ISSUE THREAD

**Issue by ansei91** [ThomasToka/MarlinFirmware#69]
Hello, dear!
I have been using your firmware for a long time since version v008.
I set up my Ender 3 S1 pro printer perfectly.
There is a problem. Flow change does not work on any of the firmwares. When I want to change the flow while printing, it simply does not change. But it will change after I start a new print. The percentage that I set in the previous print is used only after the next print is launched. I hope you understand what I'm talking about. Is it possible to make the flow change during the printing process?
Thank you very much for your hard work!

**Comment by ThomasToka** [comment]
Sorry if it does not work "live" it wont work and is not injectable into the queue. Its not a firmware bug, but by design this way.
I cant do anything here then atm.

**Comment by ansei91** [comment]
It is very inconvenient when this function does not work.
Is it possible to make this function work in real time?

**Comment by ansei91** [comment]
Tell me what this icon includes?
![Снимок](https://github.com/ThomasToka/MarlinFirmware/assets/117628472/f6e8dba9-cd44-4e23-b4d8-f14fe5216472)

**Comment by ThomasToka** [comment]
Please read my last answer regarding the flow again.

Please read the wiki: https://github.com/ThomasToka/MarlinFirmware/wiki/Display-Pages

The issue tracker is not for random questions about the firmware. Please use the discord for your questions.
