### ISSUE TITLE
Bed is not centered

### ISSUE THREAD

**Issue by 3djc** [ThomasToka/MarlinFirmware#7]
Printer: Creality Ender 3 S1 Pro
Firmware: firmware-20230417-215716-E3S1Pro-abl5x5-LA-F4

Slicer view:

![image](https://user-images.githubusercontent.com/5167938/235657191-b2c3ebfd-9b47-4a85-8366-e77204436041.png)

Printed:
![image](https://user-images.githubusercontent.com/5167938/235657481-f2166df9-c635-457c-9bb7-41d6d79e8535.png)

![image](https://user-images.githubusercontent.com/5167938/235657545-067609f4-a212-49fb-ad2d-506ef0079654.png)

**Comment by ThomasToka** [comment]
Please show me your M503, M115 and upload this gcode here.

Will have a look.

**Comment by 3djc** [comment]
I'm assuming you want the return of those two commands, but can I run them while printing ? Here is gcode already
[CE3S1PRO_Support vitre serre - side.zip](https://github.com/ThomasToka/MarlinFirmware/files/11372733/CE3S1PRO_Support.vitre.serre.-.side.zip)

**Comment by ThomasToka** [comment]
nope. connect with pronterface or any other terminal while not printing.

**Comment by 3djc** [comment]
ok, I'm using octoprint, so I have a terminal handy, but 4 hours 22 min printing left :)

**Comment by ThomasToka** [comment]
![grafik](https://user-images.githubusercontent.com/117008525/235659551-28109f13-ff92-4de3-9734-b7e2d115c187.png)

thats what i see in cura when i load your gcode. so it simply is not centered in your creality slicer. 

however.. not a firmware problem.

**Comment by 3djc** [comment]
Understood and sorry for the bogus report.. Strangely, both Creality slicer and Cura give me the same error :( Any pointer on where that setting could be (both are default install)

**Comment by ThomasToka** [comment]
probably you have your buildplate set to 220x220.

it is physical 235x235. so the firmware is set to physical dimensions.

change this and it should match.

**Comment by 3djc** [comment]
ok, will try that. Thanks a million (maybe worth adding as a side note to the installtion instructions ?)

**Comment by ThomasToka** [comment]
no problem. all cool. enjoy the firmware. join my discord if you want..

https://discord.com/invite/Fh4jsUJWe6

Edit: installation note added in readme.

**Comment by ThomasToka** [comment]
closed.
