### ISSUE TITLE
Menu stuck

### ISSUE THREAD

**Issue by GBstang** [ThomasToka/MarlinFirmware#71]
Installed firmware into my Ender3 S1 Pro F401 Chipset
I also updated the touchscreen

Issue: when going through the menu's ( I have a printer, no laser) I selected the laser to see what settings would be available, after this I tried to switch back to the printer---NO GO! no matter what I do, it will not switch back.
I reinstalled the firmware, no Bueno, reinstalled firmware for the touchscreen same same.. It will not go back to the printer menus.

**Comment by ThomasToka** [comment]
Hello,
this is not a place for user errros.
Please read the installation.txt , there you will find the discord link, join the discord and post in #installation-help.
We will try to help you there.
