### ISSUE TITLE
M425 - Backlash compensation

### ISSUE THREAD

**Issue by AbrieViljoen** [ThomasToka/MarlinFirmware#72]
Can you please enable M425 - Backlash compensation for this firmware?

**Comment by ThomasToka** [comment]
Nope. I wont. Its not supported, causing problems and the flash space used by other needed things. 

So sorry.

**Comment by AbrieViljoen** [comment]
ok, thanks for the feedback. I installed your firmware today for the first time and it looks great, thanks for all your hard work on it.
