### ISSUE TITLE
loop in menu

### ISSUE THREAD

**Issue by Vladimir101S** [ThomasToka/MarlinFirmware#73]
After attempting to exit the Leveling or Movement menu, the Max Corner SP menu opens. When trying to exit this menu, the Max ACC menu opens, where the program gets stuck. Attempting to exit this menu does nothing. I don't understand how you conducted the firmware check. This error is very frustrating for me. Firmware Ender-3S1_Pro_HighSpeed_E3S1PROFORKBYTT_Pro_Plus_v027 and firmware-20240511-075320-E3S1Plus-abl-v027-F4

**Comment by ThomasToka** [comment]
Hello,
please show me a picture of your "about" site of your printer.

**Comment by Vladimir101S** [comment]
![MUnm25RcNFs](https://github.com/ThomasToka/MarlinFirmware/assets/133904236/a8c908d6-9eb0-494e-8ca7-73aa228c0765)

**Comment by ThomasToka** [comment]
Please update the mainboard firmware to v027. you have v021.

**Comment by Vladimir101S** [comment]
...  why didn't it install.. sorry
