### ISSUE TITLE
Model visualization

### ISSUE THREAD

**Issue by Lionking86000** [ThomasToka/MarlinFirmware#74]
After Installing, the model preview and progress bar do not function. Im sure didn't miss a step

**Comment by ThomasToka** [comment]
Hello,
this issue tracker is not for user failures.
If you added a matching postprocessing script like shown here
https://github.com/ThomasToka/MarlinFirmware/wiki/Gcode-preview
and it still does not work.
Please come over to our discord server. The link is in the installation.txt
We will help you there.
