### ISSUE TITLE
Leveling

### ISSUE THREAD

**Issue by Cursealot** [ThomasToka/MarlinFirmware#79]
When i try to level the bed it goes outside the bed when probing, and showing probing failed
tried to fix it with m850 or the in print option but it keeps doing that

**Comment by Unknown-x-Enemy** [comment]
It sounds like you don't have your home offsets set correctly.

**Comment by dl200010** [comment]
Are you using a mod that moves the location of the CR Touch?

**Comment by ThomasToka** [comment]
You have not basic calibrated your printer.

Please read the installation.txt again. Especially the part "after the installation".

As this issue tracker is not for user errors i will close this as invalid.

If you need help please join the discord and post in #installation-help . 

We will help you there.
