### ISSUE TITLE
M73 progress doesn't work

### ISSUE THREAD

**Issue by Nosnahc** [ThomasToka/MarlinFirmware#8]
Hi!
I have M73 progress on my Octroprint Rpi but the touchscreen on my Ender 3-S1 Plus still show 0%.

I don't know if I'm doing wrong or if I miss something...

Btw, thank you very much for your work.

**Comment by ThomasToka** [comment]
Hello,
you probably did not install the needed plugins that send those informations.

DisplayProgress (0.1.3)
M73 Progress Plugin (0.2.1)

for example..

**Comment by Nosnahc** [comment]
I have the plugin but.. my bad, it's working.
The screen still showing "bed leveling done" but % is increasing..

**Comment by ThomasToka** [comment]
That with the bed leveling is another thing.. But its already on my todo and will be fixed in next release.
