### ISSUE TITLE
v027 back button doesn't work

### ISSUE THREAD

**Issue by sltea** [ThomasToka/MarlinFirmware#80]
MARLIN-E3S1PROFORK-BYTT-v027

Ender3S1 PLUS F4 chip

the problem occurred with both abs and url firmware.
when i try to exit any section of the menu to the main menu, the back button does not work.
and if i try to restart the device, the entered data in these menu sections, for example, probe offset, is not saved

**Comment by ThomasToka** [comment]
you need matching screen and mainboard versions 

please join the discord for user error support
