### ISSUE TITLE
Orca Slicer Error

### ISSUE THREAD

**Issue by joseto1298** [ThomasToka/MarlinFirmware#81]
Post-processing script "C:\Users\jose_\AppData\Local\Programs\Python\Python312\python.exe"
"C:\Users\jose_\AppData\Roaming\OrcaSlicer\user\default\process\E3S1PROFORKBYTT_printdat
a_orcaslicer_v20_thumbnail.py" on file
C:\Users\jose_\AppData\Local\Temp/orcaslicer_model/Sat_Sep_21/17_54_21#26816#57/Metadat
a\.26816.0.gcode.pp failed.
Error code: 1

**Comment by ThomasToka** [comment]
Please join the discord for user error support.

**Comment by joseto1298** [comment]
URL Discord

**Comment by ThomasToka** [comment]
https://discord.com/invite/Fh4jsUJWe6
