### ISSUE TITLE
Previsualiza la imagen desde octoPrint

### ISSUE THREAD

**Issue by joseto1298** [ThomasToka/MarlinFirmware#83]
I would like to see the image previewed on the screen when printing directly from ocotprint.

**Comment by Unknown-x-Enemy** [comment]
This is already possible and not an issue. Follow this and come to the discord if you have issues getting it working:
https://github.com/ThomasToka/MarlinFirmware/wiki/OctoPrint%E2%80%90E3S1PROFORKBYTT_Thumbnails-plugin

**Comment by ThomasToka** [comment]
Hello,
please use the discord for user questions.
Thank you.
