### ISSUE TITLE
V29 ABL Z Offset not saving

### ISSUE THREAD

**Issue by lin-ycv** [ThomasToka/MarlinFirmware#85]
As seen in the video, once the Z height is set, and i shut down the printer, it resets back to 0
https://github.com/user-attachments/assets/71199940-4874-4c0a-a2ab-b4b38565b6e9

I'm on S1 Pro ABL v29 F4

**Comment by ThomasToka** [comment]
Hello,
this change was done in v027 to save saves on the eeprom and is for now intended.
The save to the eeprom is done after the autoleveling run.
I will think about it if i change this to another behavior. 
But everything i do will penetrate the eeprom unneeded again.

So for now: Not a bug but a feature.

Stay tuned for v030. Maybe i touch this again.

**Comment by lin-ycv** [comment]
I see, maybe the easiest solution is to add a button for saving to eeprom?
