### ISSUE TITLE
Source code

### ISSUE THREAD

**Issue by jklap** [ThomasToka/MarlinFirmware#9]
Hello @ThomasToka -- when do you plan to update your Marlin fork repo with the changes found in the firmware you have posted here?

**Comment by ThomasToka** [comment]
When i am ready with the final release. Maybe 2 or 3 weeks.

**Comment by ThomasToka** [comment]
The source code has been released today.

https://github.com/ThomasToka/Marlin/tree/MARLIN-E3S1PROFORK-BYTT

i have also made a pull request against marlin upstream.

https://github.com/MarlinFirmware/Marlin/pull/25948

**Comment by mikep1998** [comment]
Hello, Is there a release of the final version or just RC4?

Thanks
Mike

**Comment by ThomasToka** [comment]
Binary release is tomorrow morning.
